### PR TITLE
Mvp backend

### PR DESCRIPTION
**Pull request by wsepesi**
- server side changes to actually pass data around, slight restructuring (api route as prefix for entry)
- client side connectivity, very basic data display

### CODE REVIEW

**Comment by wsepesi** [comment]
Oh also renamed "auth -> app" so it says I deleted a bunch of files but not really

**Comment by vinayvis821** [comment]
I think LGTM

**Review by jackheuberger — APPROVED** [review]
I approve but where was the oopsie

**Comment by wsepesi** [comment]
i will go to the grave with this

**Pull request merged**
